name: C/C++ CI - Build Status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make -f make
        run: make -f make -C ./3_Implementation all
